const users = [
  {
    id: 23481,
    email: 'tammy@yahoo.co.uk',
    firstName: 'Tammy',
    lastName: 'Paul',
    password: '123abc',
    type: 'staff',
    isAdmin: true,
  },
  {
    id: 23482,
    email: 'tammy@yahoo.co.uk',
    firstName: 'Tammy',
    lastName: 'Grace',
    password: '123abc',
    type: 'staff',
    isAdmin: false,
  },
  {
    id: 23483,
    email: 'tammy@yahoo.co.uk',
    firstName: 'Tammy',
    lastName: 'Miceal',
    password: '123abc',
    type: 'client',
  },
  {
    id: 23484,
    email: 'tammy@yahoo.co.uk',
    firstName: 'John',
    lastName: 'Doe',
    password: '123abc',
    type: 'client',
  },
  {
    id: 23471,
    email: 'tammy@yahoo.co.uk',
    firstName: 'John',
    lastName: 'Doe',
    password: '123abc',
    type: 'client',
  },
  {
    id: 23472,
    email: 'tammy@yahoo.co.uk',
    firstName: 'Peter',
    lastName: 'Andelis',
    password: '123abc',
    type: 'client',
  },
  {
    id: 23473,
    email: 'tammy@yahoo.co.uk',
    firstName: 'Peter',
    lastName: 'Andelis',
    password: '123abc',
    type: 'client',
  },
  {
    id: 23474,
    email: 'tammy@yahoo.co.uk',
    firstName: 'Peter',
    lastName: 'Andelis',
    password: '123abc',
    type: 'client',
  },
  {
    id: 23461,
    email: 'tammy@yahoo.co.uk',
    firstName: 'Peter',
    lastName: 'iPad',
    password: '123abc',
    type: 'client',
  },
  {
    id: 23462,
    email: 'tammy@yahoo.co.uk',
    firstName: 'Peter',
    lastName: 'iPad',
    password: '123abc',
    type: 'client',
  },
  {
    id: 23463,
    email: 'tammy@yahoo.co.uk',
    firstName: 'Peter',
    lastName: 'iPad',
    password: '123abc',
    type: 'client',
  },
  {
    id: 23451,
    email: 'tammy@yahoo.co.uk',
    firstName: 'Nokia',
    lastName: 'X',
    password: '123abc',
    type: 'client',
  },
  {
    id: 23452,
    email: 'tammy@yahoo.co.uk',
    firstName: 'Nokia',
    lastName: 'X',
    password: '123abc',
    type: 'client',
  },
  {
    id: 23453,
    email: 'tammy@yahoo.co.uk',
    firstName: 'Peter',
    lastName: 'Andelis',
    password: '123abc',
    type: 'client',
  },
  {
    id: 23441,
    email: 'tammy@yahoo.co.uk',
    firstName: 'Peter',
    lastName: 'Andelis',
    password: '123abc',
    type: 'client',
  },
  {
    id: 23442,
    email: 'tammy@yahoo.co.uk',
    firstName: 'Peter',
    lastName: 'Andelis',
    password: '123abc',
    type: 'client',
  },
  {
    id: 23443,
    email: 'tammy@yahoo.co.uk',
    firstName: 'Peter',
    lastName: 'Andelis',
    password: '123abc',
    type: 'client',
  },
  {
    id: 23444,
    email: 'tammy@yahoo.co.uk',
    firstName: 'Peter',
    lastName: 'Andelis',
    password: '123abc',
    type: 'client',
  },
  {
    id: 23445,
    email: 'tammy@yahoo.co.uk',
    firstName: 'Peter',
    lastName: 'Andelis',
    password: '123abc',
    type: 'client',
  },
  {
    id: 23431,
    email: 'tammy@yahoo.co.uk',
    firstName: 'Bright',
    lastName: 'Peter',
    password: '123abc',
    type: 'client',
  },
  {
    id: 23432,
    email: 'tammy@yahoo.co.uk',
    firstName: 'Bright',
    lastName: 'Peter',
    password: '123abc',
    type: 'client',
  },
  {
    id: 23433,
    email: 'tammy@yahoo.co.uk',
    firstName: 'Bright',
    lastName: 'Peter',
    password: '123abc',
    type: 'client',
  },
  {
    id: 23434,
    email: 'tammy@yahoo.co.uk',
    firstName: 'Bright',
    lastName: 'Peter',
    password: '123abc',
    type: 'client',
  },
  {
    id: 23491,
    email: 'tammy@yahoo.co.uk',
    firstName: 'Peter',
    lastName: 'Andelis',
    password: '123abc',
    type: 'client',
  },
  {
    id: 23492,
    email: 'tammy@yahoo.co.uk',
    firstName: 'Peter',
    lastName: 'Andelis',
    password: '123abc',
    type: 'client',
  },
  {
    id: 23493,
    email: 'tammy@yahoo.co.uk',
    firstName: 'Peter',
    lastName: 'Andelis',
    password: '123abc',
    type: 'client',
  },
  {
    id: 23494,
    email: 'tammy@yahoo.co.uk',
    firstName: 'Peter',
    lastName: 'Andelis',
    password: '123abc',
    type: 'client',
  },
  {
    id: 23494,
    email: 'tammy@yahoo.co.uk',
    firstName: 'Peter',
    lastName: 'Andelis',
    password: '123abc',
    type: 'client',
  },
  {
    id: 23421,
    email: 'tammy@yahoo.co.uk',
    firstName: 'Peter',
    lastName: 'Andela',
    password: '123abc',
    type: 'client',
  },
  {
    id: 23422,
    email: 'tammy@yahoo.co.uk',
    firstName: 'Emi',
    lastName: 'Aprekuma',
    password: '123abc',
    type: 'client',
  },
  {
    id: 23423,
    email: 'tammy@yahoo.co.uk',
    firstName: 'Omos',
    lastName: 'Paul',
    password: '123abc',
    type: 'client',
  },
];


export default users;
